<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="0" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-25T07:00:50Z" name="TmpSuite" finished-at="2021-02-25T07:00:50Z" duration-ms="193">
    <groups>
    </groups>
    <test started-at="2021-02-25T07:00:50Z" name="Register" finished-at="2021-02-25T07:00:50Z" duration-ms="52">
      <class name="com.console.RunScript">
        <test-method signature="runScript(java.lang.String)[pri:0, instance:com.console.RunScript@2692b61e]" started-at="2021-02-25T02:00:50Z" name="runScript" finished-at="2021-02-25T02:00:50Z" duration-ms="45" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[temp/Scripts/Register/Script1611241895950.groovy]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Register/Script1611241895950.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Register/Script1611241895950.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error

	at org.testng.Assert.fail(Assert.java:93)
	at com.console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.console.Execute.run(Execute.java:61)
	at com.console.RunConsole.console(RunConsole.java:59)
	at com.console.Main.main(Main.java:85)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScript -->
      </class> <!-- com.console.RunScript -->
    </test> <!-- Register -->
    <test started-at="2021-02-25T07:00:50Z" name="Login" finished-at="2021-02-25T07:00:50Z" duration-ms="26">
      <class name="com.console.RunScript">
        <test-method signature="runScript(java.lang.String)[pri:0, instance:com.console.RunScript@28d6290]" started-at="2021-02-25T02:00:50Z" name="runScript" finished-at="2021-02-25T02:00:50Z" duration-ms="26" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[temp/Scripts/Login/Script1611188057074.groovy]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Login/Script1611188057074.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Login/Script1611188057074.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error

	at org.testng.Assert.fail(Assert.java:93)
	at com.console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.console.Execute.run(Execute.java:61)
	at com.console.RunConsole.console(RunConsole.java:59)
	at com.console.Main.main(Main.java:85)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScript -->
      </class> <!-- com.console.RunScript -->
    </test> <!-- Login -->
    <test started-at="2021-02-25T07:00:50Z" name="Add Contact_Delete Contact" finished-at="2021-02-25T07:00:50Z" duration-ms="20">
      <class name="com.console.RunScript">
        <test-method signature="runScript(java.lang.String)[pri:0, instance:com.console.RunScript@64df9a61]" started-at="2021-02-25T02:00:50Z" name="runScript" finished-at="2021-02-25T02:00:50Z" duration-ms="19" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[temp/Scripts/Add Contact_Delete Contact/Script1611247483450.groovy]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error

	at org.testng.Assert.fail(Assert.java:93)
	at com.console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.console.Execute.run(Execute.java:61)
	at com.console.RunConsole.console(RunConsole.java:59)
	at com.console.Main.main(Main.java:85)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScript -->
      </class> <!-- com.console.RunScript -->
    </test> <!-- Add Contact_Delete Contact -->
    <test started-at="2021-02-25T07:00:50Z" name="Verify Existing Contacts" finished-at="2021-02-25T07:00:50Z" duration-ms="20">
      <class name="com.console.RunScript">
        <test-method signature="runScript(java.lang.String)[pri:0, instance:com.console.RunScript@7c56e013]" started-at="2021-02-25T02:00:50Z" name="runScript" finished-at="2021-02-25T02:00:50Z" duration-ms="20" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[temp/Scripts/Verify Existing Contacts/Script1611259297228.groovy]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error

	at org.testng.Assert.fail(Assert.java:93)
	at com.console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.console.Execute.run(Execute.java:61)
	at com.console.RunConsole.console(RunConsole.java:59)
	at com.console.Main.main(Main.java:85)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScript -->
      </class> <!-- com.console.RunScript -->
    </test> <!-- Verify Existing Contacts -->
  </suite> <!-- TmpSuite -->
</testng-results>
