<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="0" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-23T05:34:56Z" name="TmpSuite" finished-at="2021-02-23T05:34:56Z" duration-ms="177">
    <groups>
    </groups>
    <test started-at="2021-02-23T05:34:56Z" name="Register" finished-at="2021-02-23T05:34:56Z" duration-ms="56">
      <class name="console.RunScript">
        <test-method signature="runScript(java.lang.String)[pri:0, instance:console.RunScript@617fe9e1]" started-at="2021-02-23T00:34:56Z" name="runScript" finished-at="2021-02-23T00:34:56Z" duration-ms="44" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[temp/Scripts/Register/Script1611241895950.groovy]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Register/Script1611241895950.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Register/Script1611241895950.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Register/Script1611241895950.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Register/Script1611241895950.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors

	at org.testng.Assert.fail(Assert.java:93)
	at console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at console.Execute.run(Execute.java:61)
	at console.RunConsole.main(RunConsole.java:156)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScript -->
      </class> <!-- console.RunScript -->
    </test> <!-- Register -->
    <test started-at="2021-02-23T05:34:56Z" name="Login" finished-at="2021-02-23T05:34:56Z" duration-ms="18">
      <class name="console.RunScript">
        <test-method signature="runScript(java.lang.String)[pri:0, instance:console.RunScript@3aee3976]" started-at="2021-02-23T00:34:56Z" name="runScript" finished-at="2021-02-23T00:34:56Z" duration-ms="17" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[temp/Scripts/Login/Script1611188057074.groovy]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Login/Script1611188057074.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Login/Script1611188057074.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Login/Script1611188057074.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Login/Script1611188057074.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors

	at org.testng.Assert.fail(Assert.java:93)
	at console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at console.Execute.run(Execute.java:61)
	at console.RunConsole.main(RunConsole.java:156)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScript -->
      </class> <!-- console.RunScript -->
    </test> <!-- Login -->
    <test started-at="2021-02-23T05:34:56Z" name="Add Contact_Delete Contact" finished-at="2021-02-23T05:34:56Z" duration-ms="16">
      <class name="console.RunScript">
        <test-method signature="runScript(java.lang.String)[pri:0, instance:console.RunScript@1f130eaf]" started-at="2021-02-23T00:34:56Z" name="runScript" finished-at="2021-02-23T00:34:56Z" duration-ms="16" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[temp/Scripts/Add Contact_Delete Contact/Script1611247483450.groovy]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors

	at org.testng.Assert.fail(Assert.java:93)
	at console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at console.Execute.run(Execute.java:61)
	at console.RunConsole.main(RunConsole.java:156)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScript -->
      </class> <!-- console.RunScript -->
    </test> <!-- Add Contact_Delete Contact -->
    <test started-at="2021-02-23T05:34:56Z" name="Verify Existing Contacts" finished-at="2021-02-23T05:34:56Z" duration-ms="16">
      <class name="console.RunScript">
        <test-method signature="runScript(java.lang.String)[pri:0, instance:console.RunScript@1b5bc39d]" started-at="2021-02-23T00:34:56Z" name="runScript" finished-at="2021-02-23T00:34:56Z" duration-ms="15" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[temp/Scripts/Verify Existing Contacts/Script1611259297228.groovy]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors

	at org.testng.Assert.fail(Assert.java:93)
	at console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at console.Execute.run(Execute.java:61)
	at console.RunConsole.main(RunConsole.java:156)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScript -->
      </class> <!-- console.RunScript -->
    </test> <!-- Verify Existing Contacts -->
  </suite> <!-- TmpSuite -->
</testng-results>
